name: Build

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - run: deno lint

  Compile-Linux:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - run: deno compile --output executable --allow-read --allow-net git-scraper.ts
      - uses: actions/upload-artifact@v2
        with:
          name: my-executable
          path: $PWD/executable


          
# --target <target> 
# Target OS architecture [possible values: x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]
